# Generated by Django 5.0.7 on 2024-09-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryType', models.CharField(max_length=255)),
                ('numberOfRooms', models.IntegerField()),
                ('pricePerDay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('asset1', models.URLField(blank=True, null=True)),
                ('asset2', models.URLField(blank=True, null=True)),
                ('asset3', models.URLField(blank=True, null=True)),
                ('asset4', models.URLField(blank=True, null=True)),
                ('asset5', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guestName', models.CharField(max_length=255)),
                ('guestEmail', models.EmailField(max_length=254)),
                ('guestPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=255)),
                ('hotelAddress', models.CharField(max_length=255)),
                ('hotelPhone', models.CharField(max_length=20)),
                ('hotelEmail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('isCancelled', models.BooleanField(default=False)),
                ('isRefund', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False, editable=False)),
                ('payment_mail_sent', models.BooleanField(default=False, editable=False)),
                ('cancellation_mail_sent', models.BooleanField(default=False, editable=False)),
                ('refund_mail_sent', models.BooleanField(default=False, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guest')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
        ),
    ]
